cloudinit-userdata: |
  yum_repos:
    epel-release:
      baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
      enabled: true
      failovermethod: priority
      gpgcheck: true
      gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
      name: Extra Packages for Enterprise Linux 7 - Release
  preruncmd:
    - yum --setopt=proxy=http://proxy.corporate.com:8080 -y install epel-release redhat-lsb-core sudo openssh-server python36-virtualenv python36-PyYAML python3 snapd
    - echo "proxy=http://proxy.corporate.com:8080" >> /etc/yum.conf
  postruncmd:
    - usermod -p '*' ubuntu
    - systemctl start sshd
    - systemctl enable sshd
    - systemctl start snapd
    - systemctl enable snapd

http-proxy: http://proxy.corporate.com:8080
https-proxy: http://proxy.corporate.com:8080
snap-http-proxy: http://proxy.corporate.com:8080
snap-https-proxy: http://proxy.corporate.com:8080
