cloudinit-userdata: |
  packages:
    - python3
    - python36-PyYAML
    - python36-virtualenv
    - openssh-server
    - sudo
    - redhat-lsb-core
    - epel-release
    - snapd
  yum_repos:
    epel-release:
      baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
      enabled: true
      failovermethod: priority
      gpgcheck: true
      gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
      name: Extra Packages for Enterprise Linux 7 - Release
  postruncmd:
    - usermod -p '*' ubuntu
    - systemctl start sshd
    - systemctl enable sshd
    - systemctl start snapd
    - systemctl enable snapd
